//
//  Constants.h
//  Mapwize Tester
//
//  Created by Laszlo Blum on 2019. 03. 14..
//

#ifndef Constants_h
#define Constants_h

FOUNDATION_EXPORT NSString *const CBK_FIELD_EVENT;
FOUNDATION_EXPORT NSString *const CBK_FIELD_ARG;

FOUNDATION_EXPORT NSString *const CBK_EVENT_TAP_ON_PLACE_INFORMATION_BUTTON;
FOUNDATION_EXPORT NSString *const CBK_EVENT_TAP_ON_PLACES_INFORMATION_BUTTON;
FOUNDATION_EXPORT NSString *const CBK_EVENT_DID_TAP_ON_FOLLOW_WITHOUT_LOCATION;
FOUNDATION_EXPORT NSString *const CBK_EVENT_DID_TAP_ON_MENU;

FOUNDATION_EXPORT NSString *const CBK_EVENT_SHOULD_SHOW_INFORMATION_BUTTON_FOR;


FOUNDATION_EXPORT NSString *const CBK_EVENT_DID_LOAD;

#endif /* Constants_h */
