//
//  Constants.h
//  Mapwize Tester
//
//  Created by Laszlo Blum on 2019. 03. 14..
//

#ifndef Constants_h
#define Constants_h

FOUNDATION_EXPORT NSString *const CBK_FIELD_EVENT;
FOUNDATION_EXPORT NSString *const CBK_FIELD_ARG;

FOUNDATION_EXPORT NSString *const CBK_EVENT_TAP_ON_PLACE_INFORMATION_BUTTON;
FOUNDATION_EXPORT NSString *const CBK_EVENT_TAP_ON_PLACES_INFORMATION_BUTTON;
FOUNDATION_EXPORT NSString *const CBK_EVENT_DID_TAP_ON_FOLLOW_WITHOUT_LOCATION;
FOUNDATION_EXPORT NSString *const CBK_EVENT_DID_TAP_ON_MENU;
FOUNDATION_EXPORT NSString *const CBK_EVENT_SHOULD_SHOW_INFORMATION_BUTTON_FOR;
FOUNDATION_EXPORT NSString *const CBK_EVENT_DID_LOAD;

FOUNDATION_EXPORT NSString *const CBK_FIELD_ERR_MESSAGE;
FOUNDATION_EXPORT NSString *const CBK_FIELD_ERR_LOCALIZED_MESSAGE;

FOUNDATION_EXPORT NSString *const CBK_SET_PLACE_STYLE;
FOUNDATION_EXPORT NSString *const CBK_SET_PLACE_STYLE_ID;

FOUNDATION_EXPORT NSString *const CBK_SELECT_PLACE;
FOUNDATION_EXPORT NSString *const CBK_SELECT_PLACE_ID;
FOUNDATION_EXPORT NSString *const CBK_SELECT_PLACE_CENTERON;

FOUNDATION_EXPORT NSString *const CBK_SELECT_PLACELIST;
FOUNDATION_EXPORT NSString *const CBK_SELECT_PLACELIST_ID;

FOUNDATION_EXPORT NSString *const CBK_GRANT_ACCESS;
FOUNDATION_EXPORT NSString *const CBK_GRANT_ACCESS_TOKEN;
FOUNDATION_EXPORT NSString *const CBK_GRANT_ACCESS_SUCCESS;

FOUNDATION_EXPORT NSString *const CBK_UNSELECT_CONTENT;

FOUNDATION_EXPORT NSString *const CBK_EVENT_CLOSE_BUTTON_CLICKED;

#endif /* Constants_h */
